name: example

on: 
  push:
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build native with Maven
      run: mvn -B package
