name: Night workflow

on:
  schedule:
    - cron: '25 4 * * *' 

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build native with Maven
      run: mvn -B package
